### ISSUE TITLE
Update Indexes

### ISSUE THREAD

**Issue by RenatoCaenaro** [PetroProtsyk/FullTextSearch#1]
Hello, 
what is the best way to update indexes and not to rebuilt them everytime?
Thx!

**Comment by PetroProtsyk** [comment]
Hello,

 You can add new documents to the index by just using builder class with the same arguments multiple times:
```
                using (var builder = new PersistentBuilder("."))
                {
                    builder.Start();
                    builder.AddDocument(text, metadata);
                    builder.StopAndWait();
                }
```
It is better to add new documents in batches, otherwise speed of search operations will start to degrade.  

There is no way to update existing documents at the moment.
